### ISSUE TITLE
--short is weird

### ISSUE THREAD

**Issue by fee1-dead** [cafkafk/fortune-kind#78]
I installed this from nixpkgs version 0.1.13 and it always prints "1" (with `fortune-kind --short`) before printing the fortune, and then sometimes it would print nothing at all. The other options don't seem to have this peculiar behavior.

**Comment by cafkafk** [comment]
Ohh yea, that is weird, and broken... thanks for reporting!

**Comment by Alexuty07** [comment]
I still get this strange 1 when i use the `--short` option. My version as reported by `fortune -V` is `fortune-kind 0.1.13`. Any ideas why this might be? Here's an example output. I'm using NixOS 24.11.
```
alexuty@primus:~/ > fortune -s
1
A truly great man will neither trample on a worm nor sneak to an emperor.
                -- B. Franklin
alexuty@primus:~/ >
```

**Comment by Alexuty07** [comment]
Also, it seems sometimes I get no fortune at all? Very interesting!
```
alexuty@primus:~/ > fortune -s
1

alexuty@primus:~/ >
```

**Comment by mitchnemirov** [comment]
This is occurring for me as well, on NixOS 25.05 with the same version as @Alexuty07.
```
❯ fortune --short
1
Parting is such sweet sorrow. -William Shakespeare
```
